// NOTE: This project uses Tailwind CSS v4, which moved to CSS-first configuration.
// The active color tokens are defined in app/globals.css via the @theme block.
// This file exists as a reference. If you ever downgrade to Tailwind v3, the
// theme below is ready to use.
//
// Utility classes generated by the palette:
//   bg-navy, text-navy, border-navy         → #32317A
//   bg-baby-blue, text-baby-blue            → #95D2EB
//   bg-cream, text-cream                    → #EBEEF2
//   bg-coral, text-coral                    → #EFA4A4
//   bg-yellow, text-yellow                  → #EBE393

import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        navy: "#32317A",
        "baby-blue": "#95D2EB",
        cream: "#EBEEF2",
        coral: "#EFA4A4",
        yellow: "#EBE393",
      },
    },
  },
  plugins: [],
};

export default config;
